name: Deploy to development env

on:
  push:
    branches:
    - dev
    paths:
    - src/**
    - public/**
    - package*.json
    - .github/workflows/deploy_development.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Node JS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Run TypeScript typecheck
      run: npm run typecheck
    - name: Run tests
      run: npm run test
    - name: Set git commit
      run: echo "REACT_APP_GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Build app
      env:
        REACT_APP_ENV: development
        REACT_APP_OSM_API_URL: ${{ secrets.REACT_APP_OSM_API_URL }}
        REACT_APP_OSM_OAUTH2_CLIENT_ID: ${{ secrets.REACT_APP_OSM_OAUTH2_CLIENT_ID }}
        REACT_APP_OSM_OAUTH2_CLIENT_SECRET: ${{ secrets.REACT_APP_OSM_OAUTH2_CLIENT_SECRET }}
        REACT_APP_BACKEND_API_URL: ${{ secrets.REACT_APP_BACKEND_API_URL_NEW }}
      run: npm run build
    - name: Create robots.txt
      run: |
        cat << 'EOF' >> build/robots.txt
        # https://www.robotstxt.org/robotstxt.html
        User-agent: *
        Disallow: /
        EOF
    - name: test
      continue-on-error: true
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST_NEW_IP }}
        username: ${{ secrets.SSH_USER_NEW }}
        port: ${{ secrets.SSH_HOST_NEW_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "build/*"
        target: "~/dev-static/"
    - name: retry
        continue-on-error: true
        id: retry1
        if: steps.test.outcome=='failure'         # check the step outcome, retry 1st time
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST_NEW_IP }}
          username: ${{ secrets.SSH_USER_NEW }}
          port: ${{ secrets.SSH_HOST_NEW_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/*"
          target: "~/dev-static/"
    - name: retry 2
        continue-on-error: true
        id: retry2
        if: steps.retry1.outcome=='failure'   # check the step outcome, retry 2nd time
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST_NEW_IP }}
          username: ${{ secrets.SSH_USER_NEW }}
          port: ${{ secrets.SSH_HOST_NEW_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/*"
          target: "~/dev-static/"
      - name: retry 3
        continue-on-error: true
        id: retry3
        if: steps.retry2.outcome=='failure'      # check the step outcome, retry 3rd time
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST_NEW_IP }}
          username: ${{ secrets.SSH_USER_NEW }}
          port: ${{ secrets.SSH_HOST_NEW_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/*"
          target: "~/dev-static/"
        